SOFTWARE := "sor24-star"
DOCKERFILE := "../Dockerfile.multi"

VERSION := `basename $(pwd)`

emit-dockerfile:
    @echo {{DOCKERFILE}}

build-docker:
  docker buildx build --compress --progress plain \
  -t "{{SOFTWARE}}" \
  -f {{DOCKERFILE}} \
  . \
  --build-arg VERSION="{{VERSION}}"